import type { Member, TaskItem, RewardItem } from '../types';

export const INITIAL_MEMBERS: Member[] = [
  {
    id: 'm1',
    name: 'Bubu (Vợ iu)',
    character: 'bubu',
    role: 'Nữ hoàng việc nhà',
    points: 120,
    streak: 5,
    avatarSticker: '/stickers/bubu_solo_hat.png',
  },
  {
    id: 'm2',
    name: 'Dudu (Chồng iu)',
    character: 'dudu',
    role: 'Chiến thần dọn dẹp',
    points: 85,
    streak: 3,
    avatarSticker: '/stickers/dudu_solo_bag.png',
  },
  {
    id: 'm3',
    name: 'Bé Bông',
    character: 'baby_bear',
    role: 'Bé ngoan chăm học',
    points: 60,
    streak: 4,
    avatarSticker: '/stickers/bubu_mochi.png',
  },
];

export const INITIAL_TASKS: TaskItem[] = [
  // Việc Nhà (+)
  {
    id: 't1',
    title: 'Hút bụi & lau nhà sạch bóng',
    points: 25,
    category: 'housework',
    icon: '🧹',
    description: 'Lau dọn phòng khách và phòng ngủ thơm tho',
    timesCompleted: 14,
    stickerImage: '/stickers/gardening_housework.png',
  },
  {
    id: 't2',
    title: 'Rửa bát sạch bong kin kít',
    points: 20,
    category: 'housework',
    icon: '🍽️',
    description: 'Rửa sạch bát đĩa ngay sau khi ăn',
    timesCompleted: 22,
  },
  {
    id: 't3',
    title: 'Giặt & phơi / gấp quần áo gọn gàng',
    points: 20,
    category: 'housework',
    icon: '🧺',
    description: 'Phân loại đồ giặt và gấp cất vào tủ',
    timesCompleted: 11,
  },
  {
    id: 't4',
    title: 'Nấu bữa cơm ngon lành',
    points: 30,
    category: 'housework',
    icon: '🍳',
    description: 'Vào bếp chuẩn bị bữa ăn ấm cúng cho cả nhà',
    timesCompleted: 8,
  },
  {
    id: 't5',
    title: 'Đổ rác & thay túi rác mới',
    points: 10,
    category: 'housework',
    icon: '🗑️',
    description: 'Vứt rác đúng nơi quy định',
    timesCompleted: 19,
  },

  // Học tập & Công việc (+)
  {
    id: 't6',
    title: 'Tự giác hoàn thành bài tập về nhà',
    points: 30,
    category: 'study_work',
    icon: '📚',
    description: 'Làm hết bài tập trước giờ cơm tối',
    timesCompleted: 9,
    stickerImage: '/stickers/walking_flag.png',
  },
  {
    id: 't7',
    title: 'Đọc sách 20 phút',
    points: 15,
    category: 'study_work',
    icon: '📖',
    description: 'Nuôi dưỡng thói quen đọc sách hàng ngày',
    timesCompleted: 6,
  },

  // Thói quen tốt & Sức khỏe (+)
  {
    id: 't8',
    title: 'Đi ngủ sớm trước 22:30',
    points: 15,
    category: 'habits',
    icon: '🌙',
    description: 'Không thức khuya xem điện thoại',
    timesCompleted: 15,
  },
  {
    id: 't9',
    title: 'Uống đủ 2 lít nước mỗi ngày',
    points: 10,
    category: 'habits',
    icon: '💧',
    description: 'Giữ cơ thể luôn khỏe khoắn',
    timesCompleted: 18,
  },
  {
    id: 't10',
    title: 'Tập thể dục 30 phút & chăm sóc bản thân',
    points: 20,
    category: 'habits',
    icon: '🏃',
    description: 'Rèn luyện sức khỏe và thư giãn',
    timesCompleted: 5,
    stickerImage: '/stickers/skincare_beauty.png',
  },

  // Tình cảm & Yêu thương (+)
  {
    id: 't11',
    title: 'Massage / Đấm lưng 15 phút',
    points: 25,
    category: 'love_caring',
    icon: '💆',
    description: 'Chăm sóc người thương sau một ngày mệt mỏi',
    timesCompleted: 7,
    stickerImage: '/stickers/massage.png',
  },
  {
    id: 't12',
    title: 'Ôm một cái thật chặt & nói lời yêu',
    points: 15,
    category: 'love_caring',
    icon: '🥰',
    description: 'Nạp năng lượng hạnh phúc cho cả nhà',
    timesCompleted: 26,
    stickerImage: '/stickers/warm_hug.png',
  },

  // Việc nhắc nhở / Phạt (-)
  {
    id: 'p1',
    title: 'Chưa làm xong bài tập về nhà',
    points: -25,
    category: 'penalty',
    icon: '📝',
    description: 'Lười biếng bị cô giáo hoặc bố mẹ nhắc nhở',
    timesCompleted: 2,
    stickerImage: '/stickers/grumpy_dudu.png',
  },
  {
    id: 'p2',
    title: 'Bày bừa đồ đạc không chịu dọn',
    points: -15,
    category: 'penalty',
    icon: '🧦',
    description: 'Vứt tất, quần áo hoặc đồ chơi lung tung',
    timesCompleted: 5,
    stickerImage: '/stickers/grumpy_dudu.png',
  },
  {
    id: 'p3',
    title: 'Thức khuya lướt điện thoại / chơi game',
    points: -20,
    category: 'penalty',
    icon: '📱',
    description: 'Cố tình thức sau 23:30 gây mệt mỏi',
    timesCompleted: 3,
    stickerImage: '/stickers/grumpy_dudu.png',
  },
  {
    id: 'p4',
    title: 'Quên rửa bát / Ngâm bát qua đêm',
    points: -20,
    category: 'penalty',
    icon: '🥣',
    description: 'Bát đũa để bốc mùi trong bồn rửa',
    timesCompleted: 1,
    stickerImage: '/stickers/grumpy_dudu.png',
  },
  {
    id: 'p5',
    title: 'Cáu gắt / Giận dỗi vô cớ',
    points: -25,
    category: 'penalty',
    icon: '😤',
    description: 'Làm không khí gia đình bị chùng xuống',
    timesCompleted: 2,
    stickerImage: '/stickers/grumpy_dudu.png',
  },
];

export const INITIAL_REWARDS: RewardItem[] = [
  {
    id: 'r1',
    title: '1 Ly Trà Sữa Full Topping',
    cost: 50,
    icon: '🧋',
    description: 'Người còn lại phải mời 1 ly trà sữa theo ý thích!',
    redeemedCount: 6,
    stickerImage: '/stickers/bubu_dudu_pair.png',
  },
  {
    id: 'r2',
    title: 'Vé Miễn Rửa Bát 1 Bữa',
    cost: 40,
    icon: '🎟️',
    description: 'Dùng vé này thì hôm nay được ngồi chơi xơi nước sau ăn cơm',
    redeemedCount: 8,
    stickerImage: '/stickers/gardening_housework.png',
  },
  {
    id: 'r3',
    title: 'Suất Massage Đấm Lưng VIP 20 phút',
    cost: 60,
    icon: '💆',
    description: 'Được phục vụ tận răng kèm tinh dầu thơm ngát',
    redeemedCount: 4,
    stickerImage: '/stickers/massage.png',
  },
  {
    id: 'r4',
    title: 'Được Chọn Phim / Đi Lượn Phố',
    cost: 50,
    icon: '🎬',
    description: 'Toàn quyền chọn phim ở rạp hoặc lượn phố ăn vặt',
    redeemedCount: 3,
    stickerImage: '/stickers/scooter_ride.png',
  },
  {
    id: 'r5',
    title: '1 Giờ Thảnh Thơi (Chơi Game/Lướt Mạng)',
    cost: 35,
    icon: '🎮',
    description: 'Không bị ai sai vặt hay nhờ vả trong 1 tiếng',
    redeemedCount: 5,
    stickerImage: '/stickers/cuddle_mochi.png',
  },
  {
    id: 'r6',
    title: 'Được Yêu Cầu Nấu Món Tủ Yêu Thích',
    cost: 90,
    icon: '🍲',
    description: 'Người ấy sẽ vào bếp nấu món bạn thèm nhất',
    redeemedCount: 2,
    stickerImage: '/stickers/walking_flag.png',
  },
  {
    id: 'r7',
    title: 'Vé "Xí Xóa Cơn Giận Dỗi & Tặng Hoa"',
    cost: 150,
    icon: '💖',
    description: 'Được dỗ dành kèm bó hoa và xí xóa mọi cơn giận',
    redeemedCount: 1,
    stickerImage: '/stickers/flowers_love.png',
  },
];
